services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=pycontw2016
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpostgres
    ports:
      - ${COMPOSE_DB_PORT:-5432}:5432

  app-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=1234
      - DJANGO_SUPERUSER_EMAIL=admin@pycon.tw
    working_dir: /app/src
    command: tail -f /dev/null
